/* A triangular number can also be generated by the formula
 * triangularNumber = n ( n + 1 ) / 2
 *
 * for any integer value of n.
 *
 * Write a program that generates a table of triangular numbers using this
 * formula. Have the program generate every fifth triangular number between
 * 5 and 50 (that is, 5, 10, 15, ..., 50) */ 

#include <stdio.h>

int main (void)
{
    int n, triangularNumber = 0;

    for (n = 5; n <= 50; n += 5)
    {
        printf ("%i\n", n * ( n + 1 ) / 2);
    }

    return 0;
}
